version: '3'
services:
  db:
    image: mysql:latest
    platform: linux/x86_64
    container_name: mercury_db
    env_file: ./mysql/mysql.env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # 環境変数設定
    environment:
      # タイムゾーンを日本時間に設定
      - TZ=Asia/Tokyo
    ports:
      - '3306:3306'
    volumes:
      # mysqlのデフォルト設定ファイルの上書き、:roでコンテナ側からは読み取り専用
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      # mysqldataにマウントすることで、コンテナを削除してもデータは残るよう設定
      - mysqldata:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mercury_db
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - '8080:80'
    links:
      - mercury_db
    networks:
      - backend
    volumes:
      - /sessions

  app:
    # イメージを指定
    image: node:16
    env_file: ./app.env
    # コンテナ名
    container_name: mercury_app
    # 環境変数を設定
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    # ホスト側ポート：コンテナ側ポート
    ports:
      - '3000:3000'
    # ソースコードを格納するフォルダをマウント
    volumes:
      - ./src:/app
      - /app/node_modules/
    # 起動時のカレントフォルダを指定
    working_dir: /app
    # 起動後に実行するコマンドを指定
    command: >
      bash -c "npm install && npm run dev"
    networks:
      - backend
    depends_on:
      - mercury-db

networks:
  backend:

volumes:
  mysqldata: